name: ves_website_jaspr
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.21.6
  jaspr_router: ^0.7.3
  jaspr_tailwind: ^0.3.4

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: static
  assets:
    - web/

